/* exercises.js — FitTrack v2 */
/* bodyPart: chest | back | shoulders | biceps | triceps | core | quads | hamstrings | glutes | calves | cardio */

const EXERCISE_DATA = [
  /* ── PUSH ─── */
  { id:'ex_bench_press',    name:'Bench Press',            nameTR:'Göğüs Presi',      category:'Push',     muscleGroup:'Göğüs',           bodyPart:'chest',      equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Sırtüstü yat, bar omuz genişliğinde tut. Göğse indir, tam uzayana kadar it.' },
  { id:'ex_incline_bench',  name:'Incline Bench Press',    nameTR:'Üst Göğüs Presi',  category:'Push',     muscleGroup:'Üst Göğüs',       bodyPart:'chest',      equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'30-45° eğimli bankta göğüs presi. Üst göğüs vurgusu için.' },
  { id:'ex_dumbbell_fly',   name:'Dumbbell Fly',           nameTR:'Göğüs Açılımı',    category:'Push',     muscleGroup:'Göğüs',           bodyPart:'chest',      equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Kolları yana açarak göğüs gerir. Hafif bükülü dirsek.' },
  { id:'ex_cable_fly',      name:'Cable Fly',              nameTR:'Kablo Fly',         category:'Push',     muscleGroup:'Göğüs',           bodyPart:'chest',      equipment:'Cable',      type:'weight',     icon:'💪', instructions:'Kablolar omuz hizasında, öne doğru kavuştur.' },
  { id:'ex_pushup',         name:'Push-Up',                nameTR:'Şınav',             category:'Push',     muscleGroup:'Göğüs, Triceps',  bodyPart:'chest',      equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Eller omuz genişliğinde, vücut düz. Göğsü yere değdir, tam uzat.' },
  { id:'ex_dips',           name:'Chest Dip',              nameTR:'Dips',              category:'Push',     muscleGroup:'Alt Göğüs',       bodyPart:'chest',      equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Paralel barlarda öne eğilerek vücudu indir ve it.' },
  { id:'ex_overhead_press', name:'Overhead Press',         nameTR:'Omuz Presi',        category:'Push',     muscleGroup:'Omuz',            bodyPart:'shoulders',  equipment:'Barbell',    type:'weight',     icon:'💪', instructions:'Ayakta, bar çeneye yakın. Başın üstüne it, kontrollü indir.' },
  { id:'ex_dumbbell_ohp',   name:'DB Shoulder Press',      nameTR:'DB Omuz Presi',     category:'Push',     muscleGroup:'Omuz',            bodyPart:'shoulders',  equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Oturarak ya da ayakta dumbbellları üste it.' },
  { id:'ex_lateral_raise',  name:'Lateral Raise',          nameTR:'Yan Omuz',          category:'Push',     muscleGroup:'Yan Omuz',        bodyPart:'shoulders',  equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Dumbbellları yanlara kaldır. Omuz hizasına kadar.' },
  { id:'ex_front_raise',    name:'Front Raise',            nameTR:'Ön Omuz Kaldırma',  category:'Push',     muscleGroup:'Ön Omuz',         bodyPart:'shoulders',  equipment:'Dumbbell',   type:'weight',     icon:'💪', instructions:'Dumbbellları öne kaldır. Omuz hizasına kadar kontrollü.' },
  { id:'ex_tricep_pushdown',name:'Tricep Pushdown',        nameTR:'Triceps Kablo',     category:'Push',     muscleGroup:'Triceps',         bodyPart:'triceps',    equipment:'Cable',      type:'weight',     icon:'💪', instructions:'Kablo makinesinde kolları aşağı it. Dirsekleri sabitle.' },
  { id:'ex_skull_crusher',  name:'Skull Crusher',          nameTR:'Triceps İzole',     category:'Push',     muscleGroup:'Triceps',         bodyPart:'triceps',    equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Sırtüstü yat, bar alın üstüne indir. Dirsekleri sabit tut.' },
  { id:'ex_tricep_dip',     name:'Tricep Dip',             nameTR:'Triceps Dips',      category:'Push',     muscleGroup:'Triceps',         bodyPart:'triceps',    equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Paralel barlarda, dirsek floransı ile it.' },
  { id:'ex_overhead_tricep',name:'Overhead Tricep Ext',    nameTR:'Üst Triceps',       category:'Push',     muscleGroup:'Triceps',         bodyPart:'triceps',    equipment:'Dumbbell',   type:'weight',     icon:'💪', instructions:'Dumbbell başın üstünde tutarak triceps uzatması.' },

  /* ── PULL ─── */
  { id:'ex_deadlift',       name:'Deadlift',               nameTR:'Ölü Kaldırış',      category:'Pull',     muscleGroup:'Sırt, Hamstring', bodyPart:'back',       equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Bar ayak önünde, kalçaları aşağı çek. Sırtı düz tut, kalça ile it.' },
  { id:'ex_pullup',         name:'Pull-Up',                nameTR:'Barfikse',           category:'Pull',     muscleGroup:'Sırt, Biceps',    bodyPart:'back',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Çubuğa sarıl, göğsü bar hizasına çek. Kontrollü in.' },
  { id:'ex_barbell_row',    name:'Barbell Row',            nameTR:'Bar Rowing',         category:'Pull',     muscleGroup:'Sırt',            bodyPart:'back',       equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'45° öne eğil, barı göbek hizasına çek. Kürek kemiklerini sık.' },
  { id:'ex_cable_row',      name:'Cable Row',              nameTR:'Kablo Rowing',       category:'Pull',     muscleGroup:'Orta Sırt',       bodyPart:'back',       equipment:'Cable',      type:'weight',     icon:'💪', instructions:'Otur, kabloya uzan. Göğse doğru çek, kürek kemiklerini birleştir.' },
  { id:'ex_lat_pulldown',   name:'Lat Pulldown',           nameTR:'Lat Pulldown',       category:'Pull',     muscleGroup:'Sırt',            bodyPart:'back',       equipment:'Cable',      type:'weight',     icon:'💪', instructions:'Geniş tutuşta bar göğse indir. Dirsekleri aşağı çek.' },
  { id:'ex_dumbbell_row',   name:'Dumbbell Row',           nameTR:'DB Rowing',          category:'Pull',     muscleGroup:'Sırt',            bodyPart:'back',       equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Tek elle banka destekli rowing.' },
  { id:'ex_shrug',          name:'Barbell Shrug',          nameTR:'Trapez',             category:'Pull',     muscleGroup:'Trapez',          bodyPart:'back',       equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Barı tutarak omuzları yukarı kaldır, 1 sn üstte tut.' },
  { id:'ex_hyperext',       name:'Hyperextension',         nameTR:'Alt Sırt',           category:'Pull',     muscleGroup:'Alt Sırt',        bodyPart:'back',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Bel köprüsünde gövdeyi indir ve kaldır.' },
  { id:'ex_bicep_curl',     name:'Bicep Curl',             nameTR:'Biceps Curl',        category:'Pull',     muscleGroup:'Biceps',          bodyPart:'biceps',     equipment:'Dumbbell',   type:'weight',     icon:'💪', instructions:'Dumbbellları sıkı tut, dirsekten bükerek curl yap.' },
  { id:'ex_hammer_curl',    name:'Hammer Curl',            nameTR:'Hammer Curl',        category:'Pull',     muscleGroup:'Biceps',          bodyPart:'biceps',     equipment:'Dumbbell',   type:'weight',     icon:'💪', instructions:'Nötr tutuş (başparmak üstte) ile curl yap.' },
  { id:'ex_barbell_curl',   name:'Barbell Curl',           nameTR:'Bar Curl',           category:'Pull',     muscleGroup:'Biceps',          bodyPart:'biceps',     equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Barı geniş tutarak curl yap.' },
  { id:'ex_concentration',  name:'Concentration Curl',     nameTR:'Konsantrasyon Curl', category:'Pull',     muscleGroup:'Biceps',          bodyPart:'biceps',     equipment:'Dumbbell',   type:'weight',     icon:'💪', instructions:'Oturarak, dirsek dize dayalı izole curl.' },
  { id:'ex_face_pull',      name:'Face Pull',              nameTR:'Arka Omuz Çekiş',   category:'Pull',     muscleGroup:'Arka Omuz',       bodyPart:'shoulders',  equipment:'Cable',      type:'weight',     icon:'💪', instructions:'İp ucunu yüze doğru çek. Dirsekler omuz hizasında, dışa aç.' },

  /* ── LEGS ─── */
  { id:'ex_squat',          name:'Squat',                  nameTR:'Squat',              category:'Legs',     muscleGroup:'Quads, Gluteus',  bodyPart:'quads',      equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Bar omuzda, kalçaları paralele kadar indir.' },
  { id:'ex_rdl',            name:'Romanian Deadlift',      nameTR:'RDL',                category:'Legs',     muscleGroup:'Hamstring',       bodyPart:'hamstrings', equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Dizler hafif bükülü, kalçaları geri it.' },
  { id:'ex_leg_press',      name:'Leg Press',              nameTR:'Bacak Presi',        category:'Legs',     muscleGroup:'Quads',           bodyPart:'quads',      equipment:'Machine',    type:'weight',     icon:'🦵', instructions:'Ayaklar omuz genişliğinde. Alt 90°e kadar indir.' },
  { id:'ex_leg_curl',       name:'Leg Curl',               nameTR:'Hamstring Curl',     category:'Legs',     muscleGroup:'Hamstring',       bodyPart:'hamstrings', equipment:'Machine',    type:'weight',     icon:'🦵', instructions:'Yüzüstü ya da oturarak topuğu kalçaya yaklaştır.' },
  { id:'ex_leg_ext',        name:'Leg Extension',          nameTR:'Quads İzole',        category:'Legs',     muscleGroup:'Quads',           bodyPart:'quads',      equipment:'Machine',    type:'weight',     icon:'🦵', instructions:'Makinede bacağı tam uzat, 1 sn tut.' },
  { id:'ex_calf_raise',     name:'Calf Raise',             nameTR:'Baldır Kaldırma',    category:'Legs',     muscleGroup:'Baldır',          bodyPart:'calves',     equipment:'Machine',    type:'weight',     icon:'🦵', instructions:'Parmak uçlarında yüksel, tam iniş. 1 sn üstte tut.' },
  { id:'ex_bulgarian',      name:'Bulgarian Split Squat',  nameTR:'Bulgar Squat',       category:'Legs',     muscleGroup:'Quads, Gluteus',  bodyPart:'quads',      equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Arka ayak banka üstünde. Ön diz 90° bükülerek.' },
  { id:'ex_hip_thrust',     name:'Hip Thrust',             nameTR:'Kalça İtme',         category:'Legs',     muscleGroup:'Gluteus',         bodyPart:'glutes',     equipment:'Barbell',    type:'weight',     icon:'🏋️', instructions:'Sırtı bankaya daya, kalçayı tavana it.' },
  { id:'ex_lunge',          name:'Lunge',                  nameTR:'Lunges',             category:'Legs',     muscleGroup:'Quads, Gluteus',  bodyPart:'quads',      equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Bir adım öne at, ön diz 90°. Geri kalk.' },
  { id:'ex_glute_bridge',   name:'Glute Bridge',           nameTR:'Gluteus Bridge',     category:'Legs',     muscleGroup:'Gluteus',         bodyPart:'glutes',     equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Sırtüstü yat, kalçayı tavana kaldır, üstte sık.' },
  { id:'ex_sumo_squat',     name:'Sumo Squat',             nameTR:'Sumo Squat',         category:'Legs',     muscleGroup:'İç But, Gluteus', bodyPart:'glutes',     equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Geniş duruş, ayak parmakları dışa. Derin squat.' },
  { id:'ex_goblet_squat',   name:'Goblet Squat',           nameTR:'Goblet Squat',       category:'Legs',     muscleGroup:'Quads, Core',     bodyPart:'quads',      equipment:'Dumbbell',   type:'weight',     icon:'🏋️', instructions:'Dumbbell göğüste tutarak squat.' },
  { id:'ex_nordic',         name:'Nordic Hamstring Curl',  nameTR:'Nordic Curl',        category:'Legs',     muscleGroup:'Hamstring',       bodyPart:'hamstrings', equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Dizler yerde sabit, gövdeyi öne bırak ve geri çek.' },

  /* ── CORE ─── */
  { id:'ex_plank',          name:'Plank',                  nameTR:'Plank',              category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Dirsek desteğiyle vücudu düz tut. Nefes al.' },
  { id:'ex_crunch',         name:'Crunch',                 nameTR:'Mekik',              category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Sırtüstü, dizler bükülü. Kürek kemiklerini kaldır.' },
  { id:'ex_cable_crunch',   name:'Cable Crunch',           nameTR:'Kablo Mekik',        category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Cable',      type:'weight',     icon:'💪', instructions:'Diz üstünde, kablo ile mekik.' },
  { id:'ex_leg_raise',      name:'Leg Raise',              nameTR:'Bacak Kaldırma',     category:'Core',     muscleGroup:'Alt Karın',       bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Sırtüstü, bacakları 90° kaldır. Kontrollü indir.' },
  { id:'ex_russian_twist',  name:'Russian Twist',          nameTR:'Rus Dönüşü',         category:'Core',     muscleGroup:'Yan Karın',       bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Otur, gövdeyi döndür. Ağırlık ile zorlaştır.' },
  { id:'ex_ab_wheel',       name:'Ab Wheel Rollout',       nameTR:'Ab Wheel',           category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Diğer',      type:'bodyweight', icon:'🤸', instructions:'Diz üstünde tekerleği öne it, geri çek.' },
  { id:'ex_hanging_knee',   name:'Hanging Knee Raise',     nameTR:'Asılı Diz Çekme',    category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Bara asıl, dizleri karına çek.' },
  { id:'ex_side_plank',     name:'Side Plank',             nameTR:'Yan Plank',          category:'Core',     muscleGroup:'Yan Karın',       bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Yan yat, dirsek desteğiyle vücudu kaldır.' },
  { id:'ex_dead_bug',       name:'Dead Bug',               nameTR:'Ölü Böcek',          category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Sırtüstü, karşı kol-bacak uzat. Bel yerde sabit.' },
  { id:'ex_dragon_flag',    name:'Dragon Flag',            nameTR:'Dragon Flag',        category:'Core',     muscleGroup:'Karın',           bodyPart:'core',       equipment:'Bodyweight', type:'bodyweight', icon:'🤸', instructions:'Banka üstünde tüm vücudu aşağı-yukarı kaldır.' },

  /* ── CARDIO ─── */
  { id:'ex_running',        name:'Running',                nameTR:'Koşu',               category:'Cardio',   muscleGroup:'Kardiyo',         bodyPart:'cardio',     equipment:'Bodyweight', type:'cardio',     icon:'🏃', instructions:'Açık ya da koşu bandında. Süre ve mesafeyi not al.' },
  { id:'ex_cycling',        name:'Cycling',                nameTR:'Bisiklet',           category:'Cardio',   muscleGroup:'Kardiyo',         bodyPart:'cardio',     equipment:'Machine',    type:'cardio',     icon:'🚴', instructions:'Bisiklet ya da spin bisiklette sabit tempo.' },
  { id:'ex_rowing_machine', name:'Rowing Machine',         nameTR:'Kürek Makinesi',     category:'Cardio',   muscleGroup:'Kardiyo, Sırt',   bodyPart:'cardio',     equipment:'Machine',    type:'cardio',     icon:'🚣', instructions:'Tüm vücut kardiyo. Bacak+gövde+kol sırası.' },
  { id:'ex_jump_rope',      name:'Jump Rope',              nameTR:'İp Atlama',          category:'Cardio',   muscleGroup:'Kardiyo',         bodyPart:'cardio',     equipment:'Diğer',      type:'cardio',     icon:'⚡', instructions:'Sürekli ritimde ip atla.' },
  { id:'ex_hiit',           name:'HIIT',                   nameTR:'HIIT',               category:'Cardio',   muscleGroup:'Kardiyo',         bodyPart:'cardio',     equipment:'Bodyweight', type:'cardio',     icon:'⚡', instructions:'Yüksek yoğunluklu interval antrenmanı.' },
  { id:'ex_stairmaster',    name:'Stairmaster',            nameTR:'Merdiven Makinesi',  category:'Cardio',   muscleGroup:'Kardiyo, Bacak',  bodyPart:'cardio',     equipment:'Machine',    type:'cardio',     icon:'🏃', instructions:'Merdiven çıkma simülatörü.' },

  /* ── ESNEKLİK ─── */
  { id:'ex_cat_cow',        name:'Cat-Cow Stretch',        nameTR:'Kedi-İnek',          category:'Esneklik', muscleGroup:'Sırt',            bodyPart:'back',       equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Dörtnala pozisyonda sırtı içbükey-dışbükey yap.' },
  { id:'ex_hip_flexor',     name:'Hip Flexor Stretch',     nameTR:'Kalça Germe',        category:'Esneklik', muscleGroup:'Kalça',           bodyPart:'glutes',     equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Öne adım at, arka kalçayı öne it.' },
  { id:'ex_hamstring_str',  name:'Hamstring Stretch',      nameTR:'Hamstring Germe',    category:'Esneklik', muscleGroup:'Hamstring',       bodyPart:'hamstrings', equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Otur, bacakları uzat, öne eğil.' },
  { id:'ex_chest_str',      name:'Chest Stretch',          nameTR:'Göğüs Germe',        category:'Esneklik', muscleGroup:'Göğüs',           bodyPart:'chest',      equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Kolları arkada kavuştur, göğsü öne it.' },
  { id:'ex_child_pose',     name:"Child's Pose",           nameTR:'Çocuk Pozu',         category:'Esneklik', muscleGroup:'Sırt, Kalça',     bodyPart:'back',       equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Diz üstünde, kollar öne uzanmış.' },
  { id:'ex_pigeon_pose',    name:'Pigeon Pose',            nameTR:'Güvercin Pozu',      category:'Esneklik', muscleGroup:'Kalça',           bodyPart:'glutes',     equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Ön bacak yatay, arka bacak uzanmış. Derin kalça.' },
  { id:'ex_quad_str',       name:'Quad Stretch',           nameTR:'Quads Germe',        category:'Esneklik', muscleGroup:'Quads',           bodyPart:'quads',      equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Ayakta dur, topuğu kalçaya çek.' },
  { id:'ex_shoulder_str',   name:'Shoulder Stretch',       nameTR:'Omuz Germe',         category:'Esneklik', muscleGroup:'Omuz',            bodyPart:'shoulders',  equipment:'Bodyweight', type:'bodyweight', icon:'🧘', instructions:'Kolu göğse çek, diğer kolun arasından geçir.' },
];

const BODY_PART_LABELS = {
  chest:'Göğüs', back:'Sırt', shoulders:'Omuz', biceps:'Biceps',
  triceps:'Triceps', core:'Karın', quads:'Quads', hamstrings:'Hamstring',
  glutes:'Gluteus', calves:'Baldır', cardio:'Kardiyo',
};
